// <auto-generated />
using ER_WPF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ER_WPF.Migrations
{
    [DbContext(typeof(PokemonDataContext))]
    [Migration("20250306111552_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ER_WPF.Models.ability", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("effect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("generation")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("short_effect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Ability");
                });

            modelBuilder.Entity("ER_WPF.Models.evolution_chain", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("from")
                        .HasColumnType("integer");

                    b.Property<int>("gender")
                        .HasColumnType("integer");

                    b.Property<string>("held_item")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("item")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("known_move")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("known_move_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("min_beauty")
                        .HasColumnType("integer");

                    b.Property<int>("min_happiness")
                        .HasColumnType("integer");

                    b.Property<int>("min_level")
                        .HasColumnType("integer");

                    b.Property<bool>("needs_overworld_rain")
                        .HasColumnType("boolean");

                    b.Property<string>("party_species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("party_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("relative_physical_stats")
                        .HasColumnType("integer");

                    b.Property<string>("time_of_day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("to")
                        .HasColumnType("integer");

                    b.Property<string>("trade_species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("trigger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("turn_upside_down")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.ToTable("Evolution_chain");
                });

            modelBuilder.Entity("ER_WPF.Models.move", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("accuracy")
                        .HasColumnType("integer");

                    b.Property<string>("ailment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ailment_chance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("crit_rate")
                        .HasColumnType("integer");

                    b.Property<string>("damage_class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("description")
                        .HasColumnType("integer");

                    b.Property<int>("drain")
                        .HasColumnType("integer");

                    b.Property<int>("effect_chance")
                        .HasColumnType("integer");

                    b.Property<int>("flinch_chance")
                        .HasColumnType("integer");

                    b.Property<int>("generation")
                        .HasColumnType("integer");

                    b.Property<int>("healing")
                        .HasColumnType("integer");

                    b.Property<int>("max_hits")
                        .HasColumnType("integer");

                    b.Property<int>("min_turns")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("power")
                        .HasColumnType("integer");

                    b.Property<int>("pp")
                        .HasColumnType("integer");

                    b.Property<int>("priority")
                        .HasColumnType("integer");

                    b.Property<int>("stat_chance")
                        .HasColumnType("integer");

                    b.Property<int>("target")
                        .HasColumnType("integer");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Move");
                });

            modelBuilder.Entity("ER_WPF.Models.pokemon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("attack")
                        .HasColumnType("integer");

                    b.Property<int>("attack_effort")
                        .HasColumnType("integer");

                    b.Property<int>("base_experience")
                        .HasColumnType("integer");

                    b.Property<string>("cry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cry_legacy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("defense")
                        .HasColumnType("integer");

                    b.Property<int>("defense_effort")
                        .HasColumnType("integer");

                    b.Property<int>("height")
                        .HasColumnType("integer");

                    b.Property<int>("hidden_ability")
                        .HasColumnType("integer");

                    b.Property<int>("hp")
                        .HasColumnType("integer");

                    b.Property<int>("hp_effort")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("order")
                        .HasColumnType("integer");

                    b.Property<int>("primary_ability")
                        .HasColumnType("integer");

                    b.Property<string>("primary_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("secondary_ability")
                        .HasColumnType("integer");

                    b.Property<string>("secondary_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("special_attack")
                        .HasColumnType("integer");

                    b.Property<int>("special_attack_effort")
                        .HasColumnType("integer");

                    b.Property<int>("special_defense")
                        .HasColumnType("integer");

                    b.Property<int>("special_defense_effort")
                        .HasColumnType("integer");

                    b.Property<int>("species")
                        .HasColumnType("integer");

                    b.Property<int>("speed")
                        .HasColumnType("integer");

                    b.Property<int>("speed_effort")
                        .HasColumnType("integer");

                    b.Property<string>("sprite_back_default")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sprite_back_female")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sprite_back_shiny")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sprite_back_shiny_female")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sprite_front_default")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sprite_front_female")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sprite_front_shiny")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sprite_front_shiny_female")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("weight")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("ER_WPF.Models.pokemon_move", b =>
                {
                    b.Property<int>("pokemon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("pokemon"));

                    b.Property<string>("learn_method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("level_learned_at")
                        .HasColumnType("integer");

                    b.Property<int>("move")
                        .HasColumnType("integer");

                    b.HasKey("pokemon");

                    b.ToTable("Pokemon_move");
                });

            modelBuilder.Entity("ER_WPF.Models.pokemon_species", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("base_happiness")
                        .HasColumnType("integer");

                    b.Property<int>("capture_rate")
                        .HasColumnType("integer");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("egg_group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("gender_rate")
                        .HasColumnType("integer");

                    b.Property<string>("genera")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("generation")
                        .HasColumnType("integer");

                    b.Property<string>("growth_rate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("habitat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("hatch_counter")
                        .HasColumnType("integer");

                    b.Property<bool>("is_baby")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_legendary")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_mythical")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("national_pokedex_number")
                        .HasColumnType("integer");

                    b.Property<int>("order")
                        .HasColumnType("integer");

                    b.Property<string>("shape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("varieties")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Pokemon_species");
                });
#pragma warning restore 612, 618
        }
    }
}
